name: Scheduled Python Script

on:
  schedule:
    - cron: '0 8 * * 1-5'  # Runs everyday
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 👈 Add this line to enable manual triggering
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'
      

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: ⏬ Check out repository with Tokens
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ST_Tokens }}  # 👈 Make sure this secret exists and has 'repo' scope

      - name: 🛠️ Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade openpyxl pandas requests matplotlib
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 🧪 Verify OpenPyXL Installation
        run: python -c "import openpyxl; print('Openpyxl version:', openpyxl.__version__)"

      - name: 🚀 Run Python scripts
        run: |
          python ST_MEXC.py
          python ST_OKX.py
          python ST_Huobi.py
          python ST_KuCoin.py
          python ST_Bitget.py
          python ST_Coinbase.py
      
          
      - name: 📤 Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.ST_Tokens }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
